config/routes.rb
Rails.application.routes.draw do
  get 'donate/payment'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  resources :messages, only: [:create]
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/:id', to: 'dashboard#show', as: 'user_profile'
  get 'jobs/search', to: 'jobs#search', as: 'search_jobs'
  root to: 'pages#home'
  devise_for :users
  resources :jobs do
    resources :applications, only: [:create, :edit, :update, :destroy] do
      member do
        patch 'application', to: 'applications#update'
        delete 'delete', to: 'applications#destroy'
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, only: %i[index, show]

  def index
    if current_user.present?
      @user_profile = User.find(current_user.id)
      @message = Message.new
    else
      redirect_to :root, alert: "You are not signed in.", status: :unauthorized
    end
  end

  def show
    @user_profile = User.find(params[:id])
    @message = Message.new(name: User.where(id: params[:id]).first.name)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="row">
	<div class="col">

<div class="center mg-top-20px">
	<div class="main-card">
		<h1>
			Welcome <%= @user_profile.name %>
		</h1>
		<p>
			Email: <%= @user_profile.email %>
		</p>
	</div>
</div>



<% @user_profile.jobs.each do |job| %>
<h2 class="text-center">Jobs created:</h2>
<div class="center mg-top-20px">
	<div class="main-card">
		<p>
			<strong>Title:</strong>
			<%= job.title %>
		</p>
		<p>
			<strong>Description:</strong>
			<%= job.description %>
		</p>
		<p>
			<strong>Company:</strong>
			<%= job.company %>
		</p>
		<p>
			<strong>Location:</strong>
			<%= job.location %>
		</p>
		<p>
			<strong>Application date:</strong>
			<%= job.application_date %>
		</p>
		<% if current_user.present? %>

      <% if job.user_id == current_user.id %>
        <br>
        <br>
        <div class="delete-job">
          <%= button_to "Destroy this job", job, method: :delete %>
        </div>
      <% end %>

    <% end %>
	</div>
</div>
<% end %>

<% @user_profile.applications.each do |application| %>
<h2 class="text-center">Applications made:</h2>
<div class="center mg-top-20px">
	<div class="main-card">
		<h3>
			Job title => <%= Job.find(application.job_id).title %>
		</h3>
		<p>
			<strong>Applicant Information:</strong>
			<%= application.applicant_information %>
		</p>
		<p>
			<strong>Resume Text:</strong>
			<%= application.resume_text %>
		</p>
		<p>
			<strong>Cover Letter:</strong>
			<%= application.cover_letter %>
		</p>
		<p>
			<strong>Application Status:</strong>
			<%= application.application_status %>
		</p>
		<p>
			<strong>Submitted At:</strong>
			<%= application.submitted_at %>
		</p>

		<% if current_user.present? %>

      <% if application.user_id == current_user.id %>
        <br>
        <br>
        <div class="delete-job">
          <%= button_to "Destroy this application", job_application_path(Job.find(application.job_id), application), method: :delete, params: { application: { application_id: application.id } } %>
        </div>
      <% end %>

    <% end %>
	</div>
</div>
<% end %>
	</div>
  <div class="col">
    <div class="center mg-top-20px">
      <div class="center main-card">
        <%= form_with url: messages_path, method: :post, model: @message do |form| %>
          <div>
            <%= form.label :name %><br>
            <%= form.text_field :name %>
          </div>
          <div>
            <%= form.label :title %><br>
            <%= form.text_field :title %>
          </div>
          <div>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
          </div>
          <div><%= form.submit %></div>
        <% end %>
      </div>
    </div>

    <% if current_user.present? %>

		<% messages = Message.where(name: @user_profile.name) %>
		<% if messages.present? %>
			<h2 class="text-center">Messages received:</h2>
		<% end %>
		 <% messages.each do |message| %>
        <div class="center mg-top-20px">
				  <div class="main-card">
					  <h3>Title: <%= message.title %></h3>
					  <p>
						  <% user = User.find(message.user_id) %>
						  <strong>By:</strong> <%= link_to user.name, controller: 'dashboard', action: 'show', id: user.id %>
            </p>
            <p>
              <strong>To:</strong> <%= link_to message.name, controller: 'dashboard', action: 'show', id: User.where(name: message.name).first.id %>
            </p>
					  <p>
						  <strong>Body:</strong>
					    <%= message.body %>
					  </p>
				  </div>
			  </div>
		  <% end %>
  		<% end %>
  		 <% if current_user.present?  %>
		<% messages = @user_profile.messages %>
		<% if messages.present? %>
			<h2 class="text-center">Messages sent:</h2>
		<% end %>
		 <% messages.each do |message| %>
        <div class="center mg-top-20px">
				  <div class="main-card">
					  <h3>Title: <%= message.title %></h3>
					  <p>
						  <% user = User.find(message.user_id) %>
						  <strong>By:</strong> <%= link_to user.name, controller: 'dashboard', action: 'show', id: user.id %>
            </p>
            <p>
              <strong>To:</strong> <%= link_to message.name, controller: 'dashboard', action: 'show', id: User.where(name: message.name).first.id %>
            </p>
					  <p>
						  <strong>Body:</strong>
					    <%= message.body %>
					  </p>
				  </div>
			  </div>
		  <% end %>
  		<% end %>
	</div>

app/views/dashboard/show.html.erb
<div class="row">
  <div class="col">

<div class="center mg-top-20px">
	<div class="main-card">
		<h1>
			Welcome to <%= @user_profile.name %> profile page!
		</h1>
		<p>
			Email: <%= @user_profile.email %>
		</p>
	</div>
</div>



<% @user_profile.jobs.each do |job| %>
<h2 class="text-center">Jobs created:</h2>
<div class="center mg-top-20px">
	<div class="main-card">
		<p>
			<strong>Title:</strong>
			<%= job.title %>
		</p>
		<p>
			<strong>Description:</strong>
			<%= job.description %>
		</p>
		<p>
			<strong>Company:</strong>
			<%= job.company %>
		</p>
		<p>
			<strong>Location:</strong>
			<%= job.location %>
		</p>
		<p>
			<strong>Application date:</strong>
			<%= job.application_date %>
		</p>
		<% if current_user.present? %>

      <% if job.user_id == current_user.id %>
        <br>
        <br>
        <div class="delete-job">
          <%= button_to "Destroy this job", job, method: :delete %>
        </div>
      <% end %>

    <% end %>
	</div>
</div>
<% end %>

<% @user_profile.applications.each do |application| %>
<h2 class="text-center">Applications made:</h2>
<div class="center mg-top-20px">
	<div class="main-card">
		<h3>
			Job title => <%= Job.find(application.job_id).title %>
		</h3>
		<p>
			<strong>Applicant Information:</strong>
			<%= application.applicant_information %>
		</p>
		<p>
			<strong>Resume Text:</strong>
			<%= application.resume_text %>
		</p>
		<p>
			<strong>Cover Letter:</strong>
			<%= application.cover_letter %>
		</p>
		<p>
			<strong>Application Status:</strong>
			<%= application.application_status %>
		</p>
		<p>
			<strong>Submitted At:</strong>
			<%= application.submitted_at %>
		</p>

		<% if current_user.present? %>

      <% if application.user_id == current_user.id %>
        <br>
        <br>
        <div class="delete-job">
          <%= button_to "Destroy this application", job_application_path(Job.find(application.job_id), application), method: :delete, params: { application: { application_id: application.id } } %>
        </div>
      <% end %>

    <% end %>
	</div>
</div>
<% end %>
  </div>

  <div class="col">
    <div class="center mg-top-20px">
    	<div class="center main-card">
		<%= form_with url: messages_path, method: :post, model: @message do |form| %>
          <div>
            <%= form.label :name %><br>
            <%= form.text_field :name %>
          </div>
          <div>
            <%= form.label :title %><br>
            <%= form.text_field :title %>
          </div>
          <div>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
          </div>
          <div><%= form.submit %></div>
        <% end %>
        </div>
    </div>
  </div>