config/routes.rb
Rails.application.routes.draw do
  get 'donate/payment'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  resources :messages, only: [:create]
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/:id', to: 'dashboard#show', as: 'user_profile'
  get 'jobs/search', to: 'jobs#search', as: 'search_jobs'
  root to: 'pages#home'
  devise_for :users
  resources :jobs do
    resources :applications, only: [:create, :edit, :update, :destroy] do
      member do
        patch 'application', to: 'applications#update'
        delete 'delete', to: 'applications#destroy'
      end
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :description, presence: true

  has_rich_text :description

  has_many :applications, dependent: :destroy
  belongs_to :user
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :limit_to_five_job_postings, only:%i[create new]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.paginate(page: params[:page], per_page: 25)
    @jobs = @jobs.where("title LIKE ? OR description LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%") if params[:query].present?
    response = HTTParty.get("https://api.itjobs.pt/job/list.json?api_key=#{ENV['IT_JOBS_API_KEY']}&limit=20", format: :plain)
    @it_jobs = JSON.parse response, symbolize_names: true
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    if current_user.role == 'job poster'
      @job = Job.new
    else
      redirect_to '/', status: :unauthorized, notice: 'You are not authorized to post jobs.'
    end
  end

  # GET /jobs/1/edit
  def edit
    if current_user.role == 'job poster'
      if Job.where('user_id = ?', current_user.id).count > 5 || @job.user_id != current_user.id
        @jobs = Job.all
        return redirect_to '/', status: :unauthorized, notice: 'You are not authorize to post more than 5 job postings.'
      end
    else
      redirect_to '/', status: :unauthorized, notice: 'You are not authorized to edit jobs.'
    end
  end

  # POST /jobs or /jobs.json
  def create
    if current_user.role == 'job poster'
      @job = Job.new(job_params)
      @job.user_id = current_user.id
      respond_to do |format|
        if @job.save
          format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
          format.json { render :show, status: :created, location: @job }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to '/', status: :unauthorized, notice: 'You are not authorized to post jobs.'
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    if current_user.role == 'job poster'
      if Job.where('user_id = ?', current_user.id).count > 5 || @job.user_id != current_user.id
        @jobs = Job.all
        return redirect_to '/', status: :unauthorized, notice: 'You are not authorize to post more than 5 job postings.'
      end

      respond_to do |format|
        if @job.update(job_params) && @job.user_id == current_user.id
          format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
          format.json { render :show, status: :ok, location: @job }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to '/', status: :unauthorized, notice: 'You are not authorized to update jobs.'
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    if current_user.role == 'job poster'
      if @job.user_id != current_user.id
        @jobs = Job.all
        return redirect_to '/', status: :unauthorized, notice: 'You are not authorize to delete this post.'
      end

      @job.destroy

      respond_to do |format|
        format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to '/', status: :unauthorized, notice: 'You are not authorized to destroy jobs.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :company, :location, :application_date)
    end

    # Only allows access to people who don't have more than 5 job postings
    def limit_to_five_job_postings
      if Job.where('user_id = ?', current_user.id).count > 5
        @jobs = Job.all
        return redirect_to '/', status: :unauthorized, notice: 'You are not authorize to post more than 5 job postings.'
      end
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="container-form-jobs">
  <%= form_with(model: job) do |form| %>
    <% if job.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

        <ul>
          <% job.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.rich_text_area :description %>
    </div>

    <div>
      <%= form.label :company, style: "display: block" %>
      <%= form.text_field :company %>
    </div>

    <div>
      <%= form.label :location, style: "display: block" %>
      <%= form.text_field :location %>
    </div>

    <div>
      <%= form.label :application_date, style: "display: block" %>
      <%= form.date_field :application_date %>
    </div>

    <div class="form-button-container">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job.description %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= job.company %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= job.location %>
  </p>

  <p>
    <strong>Application date:</strong>
    <%= job.application_date %>
  </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<h1 class="main-title">Jobs</h1>

<div class="search-container">
  <%= form_tag(jobs_path, method: :get) do %>
    <%= text_field_tag :query, params[:query], placeholder: "Enter keywords...", class: "search-input" %>
    <%= submit_tag "Search", class: "search-submit" %>
  <% end %>
</div>

<div id="jobs">

  <% if @jobs %>

    <% @jobs.each do |job| %>

      <div class="card">
        <h2 class="title">
          <%= job.title %>
        </h2>

        <h4>Created by:</h4>
        <p>
          <% user = User.find(job.user_id) %>
          <%= link_to user.name, controller: 'dashboard', action: 'show', id: user.id %>
        </p>

        <p class="description">
          <%= job.description %>
        </p>
        <p class="details">
          Company: <%= job.company %>
        </p>
        <p class="details">
          Location: <%= job.location %>
        </p>
        <p class="details">
          Application Date: <%= job.application_date %>
        </p>

        <p>
          <%= link_to "Show this job", job %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>
<div class="links-center">
  <%= will_paginate @jobs %>
</div>
<div class="links-center">
  <%= link_to "New job", new_job_path %>
</div>

<h2 class="text-center">Jobs from IT Jobs</h2>
<div id="jobs-not-center">

  <%  @it_jobs[:results].each do |it_job| %>
  <div class="card">
    <h2 class="title">
      <%= it_job[:title] %>
    </h2>

    <h4>Created by:</h4>
    <p>
      It Jobs
    </p>

    <p class="description">
      <%= sanitize(it_job[:body]) %>
    </p>
    <p class="details">
      Company: <%= it_job[:company][:name] %>
    </p>
    <p class="details">
      <% if it_job[:locations].present? %>
        <% it_job[:locations].each_with_index do |location, index| %>
          Location:
          <%= location[:name] %><br>
        <% end %>
      <% end %>
    </p>
    <p class="details">
      Application Date: <%= it_job[:publishedAt] %>
    </p>

    <p>
      <a href="https://www.itjobs.pt/">It Jobs</a>
    </p>
  </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<h1 style="text-align: center;">New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<h1 class="show-title">Single Job Post</h1>

<div class="main-card-container">

  <div class="main-card">
    <h3>Created by:</h3>
        <p>
          <% user = User.find(@job.user_id) %>
          <%= link_to user.name, controller: 'dashboard', action: 'show', id: user.id %>
        </p>
    <h2 class="title"><%= @job.title %></h2>
    <p class="description"><%= @job.description %></p>
    <p class="company-location"><%= @job.company %> | <%= @job.location %></p>
    <p class="application-date"><%= @job.application_date %></p>

    <% if current_user.present? %>

    <%= link_to "Edit this job", edit_job_path(@job), class: 'edit-job-link' %> |<% end %> <%= link_to "Back to jobs", jobs_path, class: 'back-to-jobs-link' %>

    <% if current_user.present? %>

      <% if @job.user_id == current_user.id %>
        <br>
        <br>
        <div class="delete-job">
          <%= button_to "Destroy this job", @job, method: :delete %>
        </div>
      <% end %>

    <% end %>
  </div>

  <div class="main-card">
    <h2>Applications</h2>
    <% @job.applications.each do |application| %>

      <h4>
        Application <%= application.id %>
      </h4>

      <h3>Created by:</h3>
        <p>
          <% user = User.find(application.user_id) %>
          <%= link_to user.name, controller: 'dashboard', action: 'show', id: user.id %>
        </p>

      <p>
        <strong>applicant information:</strong>
        <%= application.applicant_information %>
      </p>

      <p>
        <strong>resume text:</strong>
        <%= application.resume_text %>
      </p>

      <p>
        <strong>cover letter:</strong>
        <%= application.cover_letter %>
      </p>

      <p>
        <strong>application status:</strong>
        <%= application.application_status %>
      </p>
      <% if current_user.present? %>
        <% if @job.user_id == current_user.id %>
          <div class="application-status-buttons form-container">
            <%= button_to "Accept Application", job_application_path(@job, application), class: 'accept-button', method: :patch, params: { application: { application_status: 'Accepted' } } %>
            <%= button_to "Decline Application", job_application_path(@job, application), class: 'decline-button', method: :patch, params: { application: { application_status: 'Declined'} } %>
          </div>
        <% end %>
      <% end %>
      <p>
        <strong>submitted at:</strong>
        <%= application.submitted_at %>
      </p>
    <% end %>
  </div>

  <% if @job.present? && current_user.present? %>
    <% if @job.id != current_user.id && current_user.role == 'job seeker'%>
      <div class="main-card">
        <h2>Add a application:</h2>
        <%= form_with model: [ @job, @job.applications.build ] do |form| %>
          <p>
            <%= form.label :applicant_information %><br>
            <%= form.rich_text_area :applicant_information %>
          </p>
          <p>
            <%= form.label :resume_text %><br>
            <%= form.rich_text_area :resume_text %>
          </p>
          <p>
            <%= form.label :cover_letter %><br>
            <%= form.rich_text_area :cover_letter %>
          </p>
          <p>
            <%= form.submit %>
          </p>
        <% end %>
      </div>
    <% end %>
  <% end %>

<div>