config/routes.rb
Rails.application.routes.draw do
  get 'donate/payment'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  resources :messages, only: [:create]
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/:id', to: 'dashboard#show', as: 'user_profile'
  get 'jobs/search', to: 'jobs#search', as: 'search_jobs'
  root to: 'pages#home'
  devise_for :users
  resources :jobs do
    resources :applications, only: [:create, :edit, :update, :destroy] do
      member do
        patch 'application', to: 'applications#update'
        delete 'delete', to: 'applications#destroy'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entry level tech jobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="h-15vh">
    <div class="container-nav">
      <div class="logo">
        <h2><%= link_to "Entry level Tech jobs", pages_home_path %></h2>
      </div>
      <ul class="nav-links">
        <li class="center"><%= link_to "Dashboard", dashboard_path %></li>
        <li class="center"><%= link_to "About", pages_about_path %></li>
        <li class="center"><%= link_to "Contact", pages_contact_path %></li>
        <li class="center"><%= link_to "Jobs", jobs_path %></li>
        <li class="center"><%= link_to "Post a Job", new_job_path %></li>
        <li ><button class="btn btn-success"><%= link_to "Donate", donate_payment_path, class: 'no-link' %></button></li>
        <% if user_signed_in? %>
          <li><%= button_to "Sign Out", destroy_user_session_path, class: 'nav-btn button-primary', method: :delete %></li>
        <% else %>
          <li class="center"><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <!-- Add more menu items as needed -->
      </ul>
    </div>
  </nav>

    <% unless notice.nil? %>
      <div class="notice alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% unless alert.nil? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

      <%= yield %>
  </body>
</html>